version: '3.8'
services:
  postgresql-11:
    image: postgres:11
    # volumes:
    #   - /home/ubuntu/DockerVolumes/postgres11/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432